spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: turbine

#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false