version: '3'

services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
    - "15672:15672"
    - "5672:5672"
  database:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes