server:
  port: 0

spring:
  application:
    name: users

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:forum}?createDatabaseIfNotExist=true&useSSL=false"
    username: "${DB_USER:root}"
    password: "${DB_PASS:}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - hystrix.stream