server:
  port: 0

spring:
  application:
    name: category

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:forum}?createDatabaseIfNotExist=true&useSSL=false"
    username: "${DB_USER:root}"
    password: "${DB_PASS:}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
